# zshrc

# env
export LOCAL_SHELL_INIT=1
export LOCAL_ETC="$HOME/.local/etc"
export LOCAL_BIN="$HOME/.local/bin"
export LOCAL_OPT="$HOME/.local/opt"
export LOCAL_TEMP="$HOME/.local/temp"

export TEMP_PRE_CONF="$LOCAL_TEMP/pre.sh"
export TEMP_POST_CONF="$LOCAL_TEMP/post.sh"

function source_module() {
    local _path="$LOCAL_ETC/shell/$1.sh"
    if [ -e "$_path" ]; then
        source "$_path"
    else
        echo "$_path not exist!"
    fi
}

function source_modules() {
    for arg in "$@"; do
        source_module "$arg"
    done
}

source_module pre

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# modules
source_module zinit

[ -n "$_IS_MAC" ] && source_module macos

source_modules \
    comm \
    func \
    dotdrop \
    python \
    go \
    rust

source_module post
